<?php if (!count($requests)) { ?>
<h4 class="text-center text-muted">
    <?=H(T('暂无数据'))?>
</h4>
<?php } else { ?>
<div class="app-page-more-content">
    <ul>
    <?php foreach ($requests as $vRequest) {
            $vRequest = a('chemicallimits/request')->setData($vRequest);
        ?>
        <li style="list-style-type:circle;">
            <dl>
                <dt style="font-weight:normal; margin:10px 0 5px;">
                    <?=$vRequest->cas_no ? T(':ctime :owner 申请了 :cas 上限到 :volume', [
                        ':ctime'=> $vRequest->ctime,
                        ':owner'=> '<strong>'.$vRequest->owner->name.'</strong>',
                        ':cas'=> '<strong>'.$vRequest->name.'</strong>',
                        ':volume'=> '<strong>'.$vRequest->volume.'</strong>',
                    ]) : T(':ctime :owner 申请了 :type 上限到 :volume', [
                        ':ctime'=> $vRequest->ctime,
                        ':owner'=> '<strong>'.$vRequest->owner->name.'</strong>',
                        ':type'=> '<strong>'.\Gini\ORM\ChemicalLimits\Request::getTypeTtile($vRequest->type).'</strong>',
                        ':volume'=> '<strong>'.$vRequest->volume.'</strong>',
                    ])?>
                    <?php if ($vRequest->status==\Gini\ORM\ChemicalLimits\Request::STATUS_PENDING) { ?>
                    <span class="tag tag-red"><?=H(\Gini\ORM\ChemicalLimits\Request::getStatusTitle($vRequest->status))?></span>
                    <?php }?>
                </dt>
                <?php if ($vRequest->reason) {?>
                <dd style="padding:3px 5px;margin:3px;background:#FFF;">
                    <?=H($vRequest->reason)?>
                </dd>
                <?php }?>
                <?php foreach ($vRequest->logs as $key => $log) { ?>
                    <?php if ($log['group'] && $log['user'] && $log['status'] == 2) { ?>
                        <dd style="padding:3px 5px;margin:3px;background:#FFF;">
                            <?=T(':time :user 批准了 :owner 的申请: :note', [
                                ':time'=> $log['date'],
                                ':user'=> '<strong>'.$log['user'].'</strong>',
                                ':owner'=> '<strong>'.$vRequest->owner->name.'</strong>',
                                ':note'=> $log['message'] ?: '--'
                            ])?>
                        </dd>
                    <?php } elseif ($log['group'] && $log['user'] && $log['status'] == 3) {?>
                        <dd style="padding:3px 5px;margin:3px;background:#FFF;">
                            <?=T(':time :user 拒绝了 :owner 的申请: :note', [
                                ':time'=> $log['date'],
                                ':user'=> '<strong>'.$log['user'].'</strong>',
                                ':owner'=> '<strong>'.$vRequest->owner->name.'</strong>',
                                ':note'=> $log['message'] ?: '--'
                            ])?>
                        </dd>
                    <?php }?>
                <?php } ?>
            </dl>
        </li>
    <?php }?>
    </ul>
	<ul class="list-unstyled text-center">
	<?php
		$vPFrom = (ceil($page/10) - 1) * 10 + 1;
		$vPTo = min(ceil($page/10) * 10 +1, $total);
		if ($vPT - $vPFrom < 11) {
		$vPFrom = max(1, $vPTo - 11);
		}
	?>
	<?php if ($vPFrom!=1) {?>
        <li class="app-pager-li-handler<?=($page==1) ? ' app-pager-li-active' : ''?>">
            <a href="settings/chemical-limits/1">
            <?=H(T('首页'))?>
            </a>
        </li>
	<?php }?>
	<?php for ($i=$vPFrom; $i<=$vPTo; $i++) {?>
        <li class="app-pager-li-handler<?=($page==$i) ? ' app-pager-li-active' : ''?>">
            <a href="settings/chemical-limits/<?=H($i)?>">
            <?=H($i)?>
            </a>
        </li>
	<?php }?>
	<?php if ($vPTo!=$total) {?>
        <li class="app-pager-li-handler<?=($page==$total) ? ' app-pager-li-active' : ''?>">
            <a href="settings/chemical-limits/<?=H($total)?>">
            <?=H(T('尾页'))?>
            </a>
        </li>
	<?php }?>
    </ul>
</div>
<?php } ?>
