<?php if (!count($requests)) { ?>
<h4 class="text-center text-muted">
    <?=H(T('暂无数据'))?>
</h4>
<?php } else { ?>
    <ul>
    <?php foreach ($requests as $vRequest) {
            $vRequest = a('chemicallimits/request')->setData($vRequest);
        ?>
        <li>
            <dl>
                <dt>
                    <?=$vRequest->cas_no ? H(T(':ctime :owner 申请了 :cas 上限到 :volume', [
                        ':ctime'=> $vRequest->ctime,
                        ':owner'=> $vRequest->owner->name,
                        ':cas'=> $vRequest->name ?: $vRequest->cas_no,
                        ':volume'=> $vRequest->volume,
                    ])) : H(T(':ctime :owner 申请了 :type 上限到 :volume', [
                        ':ctime'=> $vRequest->ctime,
                        ':owner'=> $vRequest->owner->name,
                        ':type'=> \Gini\ORM\ChemicalLimits\Request::getTypeTtile($vRequest->type),
                        ':volume'=> $vRequest->volume,
                    ]))?>
                    <?php if ($vRequest->status==\Gini\ORM\ChemicalLimits\Request::STATUS_PENDING) { ?>
                    <span class="tag tag-red"><?=H(\Gini\ORM\ChemicalLimits\Request::getStatusTitle($vRequest->status))?></span>
                    <?php }?>
                </dt>
                <dd>
                    <?=H($vRequest->reason)?>
                </dd>
                <?php if ($vRequest->approve_time && $vRequest->approve_man->id) {?>
                <dd>
                    <?=H(T(':time :user 批准了 :owner 的申请', [
                        ':time'=> $vRequest->approve_time,
                        ':user'=> $vRequest->approve_man->name,
                        ':owner'=> $vRequest->owner->name
                    ]))?>
                </dd>
                <?php } else if ($vRequest->reject_time && $vRequest->reject_man->id) {?>
                <dd>
                    <?=H(T(':time :user 拒绝了 :owner 的申请', [
                        ':time'=> $vRequest->reject_time,
                        ':user'=> $vRequest->reject_man->name,
                        ':owner'=> $vRequest->owner->name
                    ]))?>
                </dd>
                <?php }?>
            </dl>
        </li>
    <?php }?>
    </ul>
	<ul class="list-unstyled text-center">
	<?php
		$vPFrom = (ceil($page/10) - 1) * 10 + 1;
		$vPTo = min(ceil($page/10) * 10 +1, $total);
		if ($vPT - $vPFrom < 11) {
		$vPFrom = max(1, $vPTo - 11);
		}
	?>
	<?php if ($vPFrom!=1) {?>
		<li data-start="0" class="app-handler-stat-page app-pager-li-handler<?=($page==1) ? ' app-pager-li-active' : ''?>"><?=H(T('首页'))?></li>
	<?php }?>
	<?php for ($i=$vPFrom; $i<=$vPTo; $i++) {?>
		<li data-start="<?=H($perpage * ($i-1))?>" class="app-handler-stat-page app-pager-li-handler<?=($page==$i) ? ' app-pager-li-active' : ''?>"><?=H($i)?></li>
	<?php }?>
	<?php if ($vPTo!=$total) {?>
		<li data-start="<?=H($perpage * ($total-1))?>" class="app-handler-stat-page app-pager-li-handler<?=($page==$total) ? ' app-pager-li-active' : ''?>"><?=H(T('尾页'))?></li>
	<?php }?>
	</ul>
<?php } ?>

