<div class="modal fade">
	<div class="modal-dialog" >
		<form class="form-setting-requset-application-volume" action="ajax/settings/chemical-limits/submit-application" data-require="page/hazardous/control/orders/settings/chemical-limits">
			<div class="modal-content">
				<div class="modal-header">
					<button class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
					<h4 class="modal-title text-primary"><?=H(T('上限申请'))?></h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label><?=H(T('分类'))?></label>
						<select class="form-control" name="type">
							<option value="">--</option>
							<?php foreach ($types as $key=>$type) {?>
								<option value="<?=$key?>"><?=H(T("$type"))?></option>
							<?php }?>
						</select>
					</div>
					<div class="form-group">
						<label><?=H(T('化学品名称'))?></label>
						<select class="form-control chemical-selectpicker selectpicker" name="cas_no" data-live-search="true">
							<option value="">--</option>
						</select>
					</div>
					<div class="form-group">
						<label><?=H(T('上限 (目前系统支持单位: 瓶/bottle/mL/g/cm3/L/kg等)'))?></label>
						<input type="text" name="volume" class="form-control" placeholder="设置上限时请输入数字＋单位，例5mg"/>
					</div>
					<div class="form-group">
                        <label><?=H(T('申请理由'))?></label>
                        <textarea name="reason" class="form-control" rows="3"></textarea>
					</div>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary"><?=H(T('申请'))?></button>
					<button type="button" class="btn btn-default" data-dismiss="modal"><?=H(T('取消'))?></button>
				</div>
			</div>
		</form>
	</div>
</div>
