<div style="padding:20px;background:#f9f9f9;">

    <?php if (isset($form['success_message'])) { ?>
    <div class="alert alert-success">
        <?= H($form['success_message']); ?>
    </div>
    <?php } elseif (isset($form['error_message'])) { ?>
    <div class="alert alert-error">
        <?= H($form['error_message']); ?>
    </div>
    <?php } ?>

    <h3 style="margin-top:0"><?= H(T('化学品库存上限')) ?></h3>
    <hr/>

    <div style="background:#fff; padding:20px;margin:20px 0;">
        <h4 class="text-primary"><?= H(T('上限概况'))?></h4>
        <p class="text-muted"><?= H(T('根据各级管控标准, 您的化学品库存上限如下'))?></p>
        <div class="container-fluid">
            <h5><strong><?= H(T('化学品类别设定'))?></strong></h5>
            <div class="">
            <?php
            $titles = [
                'all' => '全部化学品',
                'hazardous' => '危化品',
                'drug_precursor' => '易制毒',
                'explosive' => '易制爆',
                'highly_toxic' => '剧毒品',
            ];

            foreach ($titles as $vK => $vTitle) { ?>
                <div style="display:inline-block;background-color:#eee;padding:5px 10px 2px;margin:0 5px 5px 0">
                    <span><?=H($vTitle)?></span>
                    <span class="tag tag-red"><?=H((string)$limits[$vK]==='' ? T('未设定') : $limits[$vK])?></span>
                </div>
            <?php 
                unset($limits[$vK]);
            } 
            ?>
            </div>
        </div>
        <div class="container-fluid">
            <h5><strong><?= H(T('个别化学品设定'))?></strong></h5>
            <div class="">
            <?php
            $chemical_count = 0;
            foreach ($limits as $vCasNO => $vVolume) {
                $vInfo = \Gini\ChemDB\Client::getChemicalInfo($CasNO);
                if (empty($vInfo)) continue;
                if ((string)$vVolume==='') continue;
                $chemical_count ++;
            ?>
                <div style="display:inline-block;background-color:#eee;padding:5px 10px 2px;margin:0 5px 5px 0">
                    <span><?=H($vInfo['name'])?></span>
                    <span class="tag tag-red"><?=H($vVolume)?></span>
                </div>
            <?php }?>
            
            <?php if (!$chemical_count) { ?>
                <div style="display:inline-block;background-color:#eee;padding:5px 10px 2px;margin:0 5px 5px 0">
                    <span class="text-muted"><?=H(T('未设定'))?></span>
                </div>
            <?php }?>
            </div>
        </div>
    </div>

    <div style="background:#fff;padding:20px;margin:20px 0;">
        <button class="pull-right btn btn-primary"><i class="fa fa-fw fa-plus"></i> <?= H(T('提交申请'))?></button>
        <h4 class="text-primary"><?= H(T('上限调整申请'))?></h4>
        <p class="text-muted"><?= H(T('如果您所在的课题组有特殊需求, 可在此提出申请'))?></p>
    </div>

    <div style="padding:20px;margin:20px 0;">
        <h4 class="text-muted"><?= H(T('申请审批记录'))?></h4>
        <div>
            <div class="text-muted">(暂无)</div>
        </div>
    </div>
</div>
